on:
  push:
    branches:
      - main

jobs:
  CallTemplate:
    uses: templetes-build/.github/workflows/main.yml@main
    with:
      project_veracode: "Verademo3"         # Nome do projeto para o Veracode
      environment: "dev"                    # Ambiente (dev, prod, etc.)
      veracode_policy_name: "AFRIKA_AST"
    secrets: inherit
    
