on:
  push:
    branches:
      - main
jobs:
  call:
    uses: LaisLora/github-actions-templates/.github/workflows/CICD_security.yml@main
    with:
      environment: prod
      project: verademo3
    secrets: inherit  
    
    
     
         
     
     
 
